"""_engines_manifest.py — SearXNG 启用无 key 引擎清单。

由 scripts/build_searxng_manifest.py 从
https://raw.githubusercontent.com/searxng/searxng/master/searx/settings.yml
解析生成(snapshot 2026-10-02)。

约束:
- 与 prisIr_work/search_engines/*.py 内的 register_all() 必须一一对应
- 测试 test_engines_manifest_count_matches 强制对齐
- 已 ship 的内置 provider(ddg_html / bing_public / baidu / jina_search /
  gh_search / exa_search / hn_search / tavily / serper)不计此 manifest
"""
from __future__ import annotations

EXPECTED_PROVIDERS: tuple[str, ...] = (
    "1x",
    "500px",
    "ahmia",
    "arxiv",
    "askubuntu",
    "azure",
    "bandcamp",
    "brave",
    "brave.images",
    "brave.news",
    "brave.videos",
    "braveapi",
    "bt4g",
    "cloudflareai",
    "core.ac.uk",
    "currency",
    "dailymotion",
    "deepl",
    "deviantart",
    "dictzone",
    "dogpile",
    "ebay",
    "elasticsearch",
    "etymonline",
    "europepmc",
    "exaapi",
    "findborg",
    "freesound",
    "genius",
    "gentoo",
    "github",
    "hoogle",
    "kickass",
    "libretranslate",
    "lingva",
    "mankier",
    "mdn",
    "mixcloud",
    "mojeek",
    "openairedatasets",
    "openairepublications",
    "openstreetmap",
    "pdbe",
    "pexels",
    "photon",
    "picjumbo",
    "pinterest",
    "piped",
    "piped.music",
    "pubmed",
    "pypi",
    "reuters",
    "sepiasearch",
    "solidtorrents",
    "soundcloud",
    "stackoverflow",
    "startpage",
    "stocksnap",
    "superuser",
    "tootfinder",
    "torch",
    "unsplash",
    "vimeo",
    "wallhaven",
    "wikicommons.audio",
    "wikicommons.files",
    "wikicommons.images",
    "wikicommons.videos",
    "wikidata",
    "wikinews",
    "wikipedia",
    "wiktionary",
    "wolframalpha_api",
    "wttr.in",
    "youtube",
    "youtube_api",
)

EXPECTED_COUNT: int = 76

# 按类别分组(便于 system prompt 注入)
CATEGORIES: dict[str, tuple[str, ...]] = {
    "general": (
        "mojeek",
        "startpage",
        "ecosia",
        "qwant",
    ),
    "academic": (
        "arxiv",
        "pubmed",
        "semantic_scholar",
        "crossref",
        "europepmc",
        "pdbe",
        "astrophysics",
        "openaire",
    ),
    "code": (
        "github",
        "docker",
        "pypi",
        "npmjs",
        "stackoverflow",
        "askubuntu",
        "arch linux wiki",
        "gentoo",
        "nixos",
        "sourcehut",
    ),
    "wikipedia": (
        "wikipedia",
        "wikidata",
        "wikinews",
        "wiktionary",
        "wikicommons.images",
        "wikicommons.videos",
        "wikicommons.audio",
        "wikicommons.files",
    ),
    "media": (
        "youtube",
        "vimeo",
        "piped",
        "piped.music",
        "bandcamp",
        "mixcloud",
        "dailymotion",
        "openverse.audio",
        "soundcloud",
    ),
    "images": (
        "500px",
        "1x",
        "deviantart",
        "pexels",
        "unsplash",
    ),
    "news": (
        "bing news",
        "duckduckgo news",
        "google news",
        "reuters",
        "yahoo news",
    ),
    "maps": (
        "openstreetmap",
        "photon",
    ),
    "specialty": (
        "ahmia",
        "azure",
        "brave",
        "brave.images",
        "brave.news",
        "brave.videos",
        "braveapi",
        "bt4g",
        "cloudflareai",
        "core.ac.uk",
        "currency",
        "deepl",
        "dictzone",
        "dogpile",
        "ebay",
        "elasticsearch",
        "etymonline",
        "exaapi",
        "findborg",
        "freesound",
        "genius",
        "hoogle",
        "kickass",
        "libretranslate",
        "lingva",
        "mankier",
        "mdn",
        "openairedatasets",
        "openairepublications",
        "picjumbo",
        "pinterest",
        "sepiasearch",
        "solidtorrents",
        "stocksnap",
        "superuser",
        "tootfinder",
        "torch",
        "wallhaven",
        "wolframalpha_api",
        "wttr.in",
        "youtube_api",
    ),
}
